version: '1.0'
services:
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_DB: notification_mini_app
        volumes:
            - ./data:/var/lib/postgresql/data
        ports:
            - 5432:5432